// pages/friends/index.vue
<template>
	<div
		class="no-select md:grid md:grid-cols-12 md:grid-flow-row space-y-6 md:space-y-0 md:gap-6 w-full h-full px-8 pt-4 pb-8 md:py-7 md:px-12 lg:px-48 2xl:py-14 2xl:px-96"
	>
		<Card
			class="col-span-5 shadow-cyan-500/50"
			github="https://github.com/tdiant"
			avatar="https://avatars.githubusercontent.com/u/22428650"
		>
			<template #name>
				<span class="hover:text-cyan-500">tdiant</span>
			</template>
			<template #description> Current MCBBS programming section moderator, also the author of BDN. </template>
			<template #link>
				<a href="https://blog.tdiant.net/" class="hover:text-cyan-500 hover:underline" target="_blank"
					>https://blog.tdiant.net</a
				>
			</template>
		</Card>
		<Card
			class="col-span-7 shadow-indigo-500/50"
			github="https://github.com/LeSnow-Ye"
			avatar="https://avatars.githubusercontent.com/u/40481418"
		>
			<template #name>
				<span class="hover:text-indigo-500">LeSnow Ye</span>
			</template>
			<template #description> A member of MCBBS BoneStudio, who is currently studying Engineering. </template>
			<template #link>
				<a href="https://lesnow.top/" class="hover:text-indigo-500 hover:underline" target="_blank"
					>https://lesnow.top</a
				>
			</template>
		</Card>
		<Card
			class="col-span-7 shadow-pink-500/50"
			github="https://github.com/Song-Xin233"
			avatar="https://aoss.ssxx.site:21443/website/imgs/header.jpg"
		>
			<template #name>
				<span class="hover:text-pink-500">上杉夏相</span>
			</template>
			<template #description> From his blog, it is clear that he is studying medicine. </template>
			<template #link>
				<a href="https://blog.ssxx.site/" class="hover:text-pink-500 hover:underline" target="_blank"
					>https://blog.ssxx.site</a
				>
			</template>
		</Card>
		<Card
			class="col-span-5 shadow-primary-500/50"
			github="https://github.com/qyl27"
			avatar="https://avatars.githubusercontent.com/u/53731501"
		>
			<template #name>
				<span class="hover:text-pink-500">秋雨落</span>
			</template>
			<template #description> A cute girl with a fantastic soul. </template>
			<template #link>
				<a href="https://www.qy.al/" class="hover:text-primary-500 hover:underline" target="_blank"
					>https://www.qy.al</a
				>
			</template>
		</Card>
		<Card
			class="col-span-5 shadow-indigo-500/50"
			github="https://github.com/ZerolAcqua"
			avatar="https://avatars.githubusercontent.com/u/68687848"
		>
			<template #name>
				<span class="hover:text-indigo-500">Zerol Acqua</span>
			</template>
			<template #description> A really adorable unicorn who loves water magic. </template>
			<template #link>
				<a href="https://zerolacqua.top/" class="hover:text-indigo-500 hover:underline" target="_blank"
					>https://zerolacqua.top/</a
				>
			</template>
		</Card>
	</div>
</template>

<script setup>
import Card from "@/components/friends/Card.vue";
useHead({
	title: "Friends"
});
</script>

// src/routes/friends.tsx
import { createFileRoute } from "@tanstack/react-router";
import { FriendCard } from "@/components/widgets/friend-card";
import { cn } from "@/utils";

export const Route = createFileRoute("/friends")({
  head: () => ({
    meta: [
      {
        title: "Friends - E23.DEV",
      },
    ],
  }),
  component: Friends,
});

function Friends() {
  return (
    <div
      className={cn([
        [
          "no-select",
          "w-full",
          "max-w-5xl",
          "mx-auto",
          "h-full",
          "px-6",
          "md:px-10",
          "lg:px-12",
          "py-10",
          "flex",
          "flex-col",
          "gap-5",
        ],
      ])}
    >
      <div className={cn(["flex", "justify-end", "items-end", "gap-2"])}>
        <img src="/ela/meme/love.png" alt="love" width={64} draggable={false} />
        <span className={cn(["italic", "text-secondary-foreground"])}>
          Friendship is Magic!
        </span>
      </div>
      <div
        className={cn([
          "space-y-6",
          "md:space-y-0",
          "md:gap-6",
          "md:grid",
          "md:grid-cols-12",
          "md:grid-flow-row",
        ])}
      >
        <FriendCard
          name="tdiant"
          avatar="https://avatars.githubusercontent.com/u/22428650"
          description={
            "Former MCBBS programming section moderator, also the author of BDN."
          }
          link={
            <a
              href="https://nyan.best/"
              className="hover:text-cyan-500 hover:underline"
              target="_blank"
              rel="noopener"
            >
              https://nyan.best
            </a>
          }
          className={cn([
            "col-span-5",
            "shadow-cyan-600/50",
            "dark:shadow-cyan-500/50",
          ])}
        />
        <FriendCard
          name="Lesnow Ye"
          avatar="https://avatars.githubusercontent.com/u/40481418"
          description={
            "A member of former MCBBS BoneStudio, who is currently studying Engineering."
          }
          link={
            <a
              href="https://lesnow.top/"
              className="hover:text-indigo-500 hover:underline"
              target="_blank"
              rel="noopener"
            >
              https://lesnow.top
            </a>
          }
          className={cn([
            "col-span-7",
            "shadow-indigo-600/50",
            "dark:shadow-indigo-500/50",
          ])}
        />
        <FriendCard
          name="KawaiiYoumu"
          avatar="https://cos-shanghai-01-1301223281.cos.ap-shanghai.myqcloud.com/box/imgs/youmu-header.webp"
          description={
            "From his blog, it is clear that he is studying medicine."
          }
          link={
            <a
              href="https://blog.konpaku.cn/"
              className="hover:text-pink-500 hover:underline"
              target="_blank"
              rel="noopener"
            >
              https://blog.konpaku.cn
            </a>
          }
          className={cn([
            "col-span-7",
            "shadow-pink-600/50",
            "dark:shadow-pink-500/50",
          ])}
        />
        <FriendCard
          name="Zerol Acqua"
          avatar="https://cdn.zerolacqua.top/images/avatar.png"
          description={"A really adorable unicorn who skills water magic."}
          link={
            <a
              href="https://zerolacqua.top/"
              className="hover:text-emerald-500 hover:underline"
              target="_blank"
              rel="noopener"
            >
              https://zerolacqua.top
            </a>
          }
          className={cn([
            "col-span-5",
            "shadow-emerald-600/50",
            "shadow-emerald-500/50",
          ])}
        />
        <FriendCard
          name="Lenny Chen"
          avatar="https://s2.loli.net/2024/03/31/Ht3QBqhgLYNAuwj.png"
          description={
            "A friend who is passionate about the law. (MLP also, so we get to know each other.)"
          }
          link={
            <a
              href="https://lennychen.top/"
              className="hover:text-indigo-500 hover:underline"
              target="_blank"
              rel="noopener"
            >
              https://lennychen.top
            </a>
          }
          className={cn([
            "col-span-5",
            "shadow-indigo-600/50",
            "shadow-indigo-500/50",
          ])}
        />
      </div>
    </div>
  );
}
